In [1]:
import numpy as np
import pandas as pd

In [ ]:
Finding Missing Data

In [2]:
data = {
    'A': [1,np.nan,'zeal',2,3,np.nan],
    'B': [2,np.nan,'CO',4,6,np.nan],
    'C': [1,np.nan,'SIT',2,np.nan,8],
    'D': [1,np.nan,'ZCOER',np.nan,3,9]

}
df= pd.DataFrame(data)

In [3]:
df

      A    B    C      D
0     1    2    1      1
1   NaN  NaN  NaN    NaN
2  zeal   CO  SIT  ZCOER
3     2    4    2    NaN
4     3    6  NaN      3
5   NaN  NaN    8      9

In [4]:
df.isna()

       A      B      C      D
0  False  False  False  False
1   True   True   True   True
2  False  False  False  False
3  False  False  False   True
4  False  False   True  False
5   True   True  False  False

In [5]:
df.isna().sum()

A    2
B    2
C    2
D    2
dtype: int64

In [6]:
df.isna().any()

A    True
B    True
C    True
D    True
dtype: bool

In [ ]:
Removing Missimg Data #Row wise selection

In [7]:
df

      A    B    C      D
0     1    2    1      1
1   NaN  NaN  NaN    NaN
2  zeal   CO  SIT  ZCOER
3     2    4    2    NaN
4     3    6  NaN      3
5   NaN  NaN    8      9

In [8]:
df.dropna()

      A   B    C      D
0     1   2    1      1
2  zeal  CO  SIT  ZCOER

In [9]:
df.dropna(thresh=0)

      A    B    C      D
0     1    2    1      1
1   NaN  NaN  NaN    NaN
2  zeal   CO  SIT  ZCOER
3     2    4    2    NaN
4     3    6  NaN      3
5   NaN  NaN    8      9

In [10]:
df

      A    B    C      D
0     1    2    1      1
1   NaN  NaN  NaN    NaN
2  zeal   CO  SIT  ZCOER
3     2    4    2    NaN
4     3    6  NaN      3
5   NaN  NaN    8      9

In [11]:
df.dropna(thresh=5)

Empty DataFrame
Columns: [A, B, C, D]
Index: []

In [12]:
df.dropna(thresh=4)

      A   B    C      D
0     1   2    1      1
2  zeal  CO  SIT  ZCOER

In [13]:
df.dropna(thresh=2)

      A    B    C      D
0     1    2    1      1
2  zeal   CO  SIT  ZCOER
3     2    4    2    NaN
4     3    6  NaN      3
5   NaN  NaN    8      9

In [ ]:
Filling The Missing Data #columnwise selection

In [14]:
df

      A    B    C      D
0     1    2    1      1
1   NaN  NaN  NaN    NaN
2  zeal   CO  SIT  ZCOER
3     2    4    2    NaN
4     3    6  NaN      3
5   NaN  NaN    8      9

In [15]:
df.fillna('yes')

      A    B    C      D
0     1    2    1      1
1   yes  yes  yes    yes
2  zeal   CO  SIT  ZCOER
3     2    4    2    yes
4     3    6  yes      3
5   yes  yes    8      9

In [16]:
df

      A    B    C      D
0     1    2    1      1
1   NaN  NaN  NaN    NaN
2  zeal   CO  SIT  ZCOER
3     2    4    2    NaN
4     3    6  NaN      3
5   NaN  NaN    8      9

In [21]:
values={ 'A':700,'B':866,'C':500,'D':900}
df.fillna(value=values)

      A    B    C      D
0     1    2    1      1
1   700  866  500    900
2  zeal   CO  SIT  ZCOER
3     2    4    2    900
4     3    6  500      3
5   700  866    8      9

In [22]:
df

      A    B    C      D
0     1    2    1      1
1   NaN  NaN  NaN    NaN
2  zeal   CO  SIT  ZCOER
3     2    4    2    NaN
4     3    6  NaN      3
5   NaN  NaN    8      9

In [28]:
df.fillna(df.mean(numeric_only=True), inplace=True)
df

      A    B    C      D
0     1    2    1      1
1   NaN  NaN  NaN    NaN
2  zeal   CO  SIT  ZCOER
3     2    4    2    NaN
4     3    6  NaN      3
5   NaN  NaN    8      9

In [29]:
df

      A    B    C      D
0     1    2    1      1
1   NaN  NaN  NaN    NaN
2  zeal   CO  SIT  ZCOER
3     2    4    2    NaN
4     3    6  NaN      3
5   NaN  NaN    8      9

In [30]:
new_df = df.fillna(df.mean(numeric_only=True))

print(new_df)

      A    B    C      D
0     1    2    1      1
1   NaN  NaN  NaN    NaN
2  zeal   CO  SIT  ZCOER
3     2    4    2    NaN
4     3    6  NaN      3
5   NaN  NaN    8      9